apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: home-deployment
spec:
  selector:
    matchLabels:
      app: web-nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: web-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: nginx

---

kind: Service
apiVersion: v1
metadata:
  name: my-app
spec:
  selector:
    app: web-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: nginx
  type: LoadBalancer